name: coverage

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Upload coverage to codecov.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install beta --profile minimal --component llvm-tools
      - run: cargo +beta llvm-cov --all-features --codecov --output-path codecov.json
      - uses: codecov/codecov-action@v4
        with:
          files: codecov.json
          fail_ci_if_error: true
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
